server:
  port: 83

spring:
  application:
    name: consumer-nacos-order83
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 指定服务提供者注册到Nacos的名字
service-url:
  nacos-user-service: http://nacos-payment